export * from './animal-update.interface'
export * from './animal.interface'
export * from './animal-overview.interface'
export * from './farm.interface'
export * from './user.interface'
export * from './create-animal-update.interface'
export * from './animal-assignment-section.interface'
